export const LOAD_PODCAST_EPISODE = 'LOAD_PODCAST_EPISODE';
export const ADD_PODCASTS = 'ADD_PODCASTS';
export const ADD_PLAYLIST_EPISODE = 'ADD_PLAYLIST_EPISODE';
export const DELETE_PLAYLIST_EPISODE = 'DELETE_PLAYLIST_EPISODE';
